
export const API_URL_PRV = 'https://onotdivmryufzdprvgul.supabase.co/rest/v1/cripto_table'
export const SUPABASE_KEY_PRV = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ub3RkaXZtcnl1ZnpkcHJ2Z3VsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTMyODYzNCwiZXhwIjoyMDYwOTA0NjM0fQ.qTz3CwCNjMJBtHhTLf-zdsNA5AByx0wQmFWbxieOMoQ'
